DELETE FROM [dbo].[FactAlzheimersDisease]
DELETE FROM [dbo].[DimTopic]
DELETE FROM [dbo].[DimStratification2]
DELETE FROM [dbo].[DimQuestion]
DELETE FROM [dbo].[DimLocation]
DELETE FROM [dbo].[DimDataValueType]
DELETE FROM [dbo].[DimAgeGroup]